server:
  port: 8081
spring:
  application:
    name: test-service-B
  zipkin:
    base-url: http://localhost:9411

# Below are actuator configurations
management:
  tracing:
    enabled: true
  health:
    circuit breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health #to get all we can use *
  endpoint:
    health:
      show-details: always